
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=UTC
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
#  thymeleaf:
#    prefix: classpath:\templates\pages\
#    suffix: .html
mybatis-plus:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.worker0902.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml
